# Generated by Django 5.0.2 on 2025-06-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_cover_file_cover_image_alter_cover_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='file',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='image_url',
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_file',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/', verbose_name='Электронная версия книги'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
    ]
