# Generated by Django 5.0.2 on 2025-06-04 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_cover_file_remove_cover_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_url',
            field=models.URLField(blank=True, help_text='URL страницы книги на сайте издательства', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author', verbose_name='Автор'),
        ),
    ]
