# Generated by Django 5.2.1 on 2025-05-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='books.UserRole', to='books.role', verbose_name='Роли'),
        ),
    ]
