# Generated by Django 5.0.2 on 2025-06-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='book_files/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='cover',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='URL изображения'),
        ),
    ]
